'use client';
import {useEffect,useRef,useState,useCallback,type ReactNode} from 'react';
import {ArrowRight,ArrowUpRight,BookOpen,Check,CheckCheck,ChevronDown,ChevronRight,Clock3,Code2,Copy,Download,FileText,FolderOpen,Grid2X2,Image,Keyboard,Languages,Leaf,LoaderCircle,Menu,MessageSquareText,MoreHorizontal,PenLine,Plus,Search,Settings2,Sparkles,Upload,X,BarChart3,Video,Megaphone,GraduationCap,Users,House,Info,FilePlus2} from 'lucide-react';
import {Button} from './ui/button';
import {Modal} from './ui/dialog';
import {CATEGORIES} from '../src/domain';
import {type CardPrompt,type Library,type ImportJob,fillTemplate} from '../src/web/types';

const categoryIcons:Record<string,typeof FileText>={'寫作':PenLine,'報告文書':FileText,'翻譯與潤稿':Languages,'程式':Code2,'資料分析':BarChart3,'圖像生成':Image,'影音':Video,'行銷文案':Megaphone,'教學備課':GraduationCap,'生活雜務':House,'角色與人設':Users,'其他':FolderOpen};
const featuredCategories=['寫作','報告文書','翻譯與潤稿','程式','圖像生成','生活雜務'];
const categoryDescriptions:Record<string,string>={'寫作':'把想法寫成好文章','報告文書':'讓工作更有條理','翻譯與潤稿':'找到更好的表達','程式':'讓開發更有效率','圖像生成':'讓想像成為畫面','生活雜務':'把日常變得簡單'};
const pagesDemo=process.env.NEXT_PUBLIC_PAGES_DEMO==='true';
async function api<T>(url:string,options:RequestInit={}):Promise<T> {if(pagesDemo){const {browserApi}=await import('../src/web/browser-store');return browserApi<T>(url,options);}const response=await fetch(url,{...options,headers:{'Content-Type':'application/json',...options.headers}});const result=await response.json();if(!response.ok) throw new Error(result.error??'暫時無法完成，請重試');return result;}
function CategoryIcon({name,size=19}:{name:string;size?:number}) {const Icon=categoryIcons[name]??FileText;return <Icon size={size} strokeWidth={1.7}/>;}
function relativeDate(value:string|null) {if(!value) return '還沒使用過';const minutes=Math.max(0,Math.floor((Date.now()-Date.parse(value))/60000));return minutes<1?'剛剛使用':minutes<60?`${minutes} 分鐘前`:minutes<1440?`${Math.floor(minutes/60)} 小時前`:`${Math.floor(minutes/1440)} 天前`;}
function Highlight({value}:{value:NonNullable<CardPrompt['highlight']>}) {const parts:ReactNode[]=[];let at=0;value.ranges.forEach(([start,end],i)=>{parts.push(value.text.slice(at,start),<mark key={i}>{value.text.slice(start,end)}</mark>);at=end;});parts.push(value.text.slice(at));return <>{parts}</>;}

export default function PromptApp() {
  const [view,setView]=useState<'home'|'library'|'recent'>('home'),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[tag,setTag]=useState(''),[sort,setSort]=useState('all');
  const [data,setData]=useState<Library|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
  const [detail,setDetail]=useState<CardPrompt|null>(null),[importOpen,setImportOpen]=useState(false),[helpOpen,setHelpOpen]=useState(false),[mobileNav,setMobileNav]=useState(false),[allCategories,setAllCategories]=useState(false);
  const [toast,setToast]=useState(''),[selected,setSelected]=useState(-1),[installEvent,setInstallEvent]=useState<any>(null);
  const searchRef=useRef<HTMLInputElement>(null),toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null),resultsRef=useRef<HTMLDivElement>(null);
  const notify=useCallback((message:string)=>{setToast(message);if(toastTimer.current) clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4500);},[]);
  const reload=()=>setRefresh(v=>v+1);
  const home=view==='home'&&!query&&!category&&!tag;
  useEffect(()=>{
    const controller=new AbortController();setLoading(true);setError('');setSelected(-1);
    const timer=setTimeout(()=>{api<Library>('/api/library?'+new URLSearchParams({q:query,category,tag,sort:view==='recent'?'recent':sort}),{signal:controller.signal}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},query?180:0);
    return()=>{clearTimeout(timer);controller.abort();};
  },[query,category,tag,sort,view,refresh]);
  useEffect(()=>{if(!pagesDemo&&'serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(()=>{});const handler=(event:Event)=>{event.preventDefault();setInstallEvent(event);};window.addEventListener('beforeinstallprompt',handler);return()=>{window.removeEventListener('beforeinstallprompt',handler);if(toastTimer.current)clearTimeout(toastTimer.current);};},[]);
  const navigate=(next:'home'|'library'|'recent',nextCategory='')=>{setView(next);setQuery('');setCategory(nextCategory);setTag('');setSort('all');setMobileNav(false);};
  const usePrompt=async(p:CardPrompt)=>{
    if(p.variables.length){setDetail(p);return;}
    try{await navigator.clipboard.writeText(p.body);try{await api('/api/prompts/'+p.id,{method:'POST',body:JSON.stringify({action:'use',values:{},eventId:crypto.randomUUID()})});notify('已複製，貼上就能開始使用');reload();}catch{notify('已複製，但使用紀錄暫時未儲存');}}catch{setDetail(p);notify('瀏覽器未允許複製，請在預覽中選取文字');}
  };
  useEffect(()=>{
    const handler=(event:KeyboardEvent)=>{
      if(detail||importOpen||helpOpen||event.isComposing)return;
      const target=event.target as HTMLElement,editable=['INPUT','TEXTAREA','SELECT'].includes(target.tagName)||target.isContentEditable;
      if(event.key==='/'&&!editable){event.preventDefault();searchRef.current?.focus();return;}
      if((editable&&target!==searchRef.current)||!data?.items.length)return;
      if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();setSelected(index=>{const next=Math.max(0,Math.min(data.items.length-1,index+(event.key==='ArrowDown'?1:-1)));resultsRef.current?.querySelectorAll('[data-prompt-card]')[next]?.scrollIntoView({block:'nearest',behavior:'smooth'});return next;});}
      if(event.key==='Enter'&&selected>=0){event.preventDefault();void usePrompt(data.items[selected]);}
    };window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);
  });
  const recent=data?.items.filter(p=>p.last_used).sort((a,b)=>(b.last_used??'').localeCompare(a.last_used??'')).slice(0,3)??[];
  const visible=home?(recent.length?recent:data?.items.slice(0,3)??[]):data?.items??[];
  return <div className="app-shell">
    {mobileNav&&<button className="nav-scrim" aria-label="關閉導覽" onClick={()=>setMobileNav(false)}/>}
    <aside className={`sidebar ${mobileNav?'sidebar-open':''}`}>
      <button className="brand" onClick={()=>navigate('home')} aria-label="Prompt 辭典首頁"><span className="brand-mark"><BookOpen size={23} strokeWidth={1.65}/></span><span>Prompt 辭典<small>YOUR IDEAS, READY TO USE.</small></span></button>
      <div className="workspace-label"><span className="workspace-dot"/>個人工作空間<span className="workspace-tag">LOCAL</span></div>
      <nav aria-label="主導覽" className="main-nav">
        <button className={view==='home'?'active':''} onClick={()=>navigate('home')}><Search size={19}/>探索與搜尋</button>
        <button className={view==='library'&&!category?'active':''} onClick={()=>navigate('library')}><BookOpen size={19}/>我的辭典<span className="nav-count">{data?.total??'—'}</span></button>
        <button className={view==='recent'?'active':''} onClick={()=>navigate('recent')}><Clock3 size={19}/>最近使用</button>
      </nav>
      <div className="nav-divider"/><div className="section-eyebrow sidebar-heading">依分類瀏覽</div>
      <nav className="category-nav" aria-label="分類導覽">{featuredCategories.map(name=><button className={category===name?'active':''} key={name} onClick={()=>navigate('library',name)}><CategoryIcon name={name} size={17}/><span>{name}</span><small>{data?.categories.find(c=>c.name===name)?.count??0}</small></button>)}<button onClick={()=>{navigate('home');setAllCategories(true);}}><MoreHorizontal size={18}/><span>所有分類</span><small>12</small></button></nav>
      <div className="sidebar-bottom"><div className="collect-note"><span className="note-leaf"><Leaf size={21}/></span><strong>讓好用的 Prompt，<br/>有個自己的家。</strong><p>把散落的靈感收進辭典，<br/>下次需要時，一找就有。</p><button onClick={()=>setImportOpen(true)}>匯入我的 Prompt<ArrowUpRight size={15}/></button></div>
        <button className="profile" onClick={()=>setHelpOpen(true)}><span className="avatar">我</span><span>我的個人辭典<small><i/>{pagesDemo?'資料儲存在此瀏覽器':'資料儲存在這台電腦'}</small></span><Settings2 size={17}/></button>
      </div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" onClick={()=>setMobileNav(true)} aria-label="開啟導覽"><Menu size={21}/></button><span>我的工作空間</span><ChevronRight size={13}/><strong>{view==='recent'?'最近使用':category|| (view==='library'?'我的辭典':'探索與搜尋')}</strong></div><div className="top-actions">{installEvent&&<Button variant="ghost" size="sm" onClick={async()=>{await installEvent.prompt();setInstallEvent(null);}}><Download size={16}/>安裝 App</Button>}<button className="shortcut-help" onClick={()=>setHelpOpen(true)} aria-label="操作說明與快捷鍵"><Keyboard size={18}/><span>快捷鍵</span></button><Button size="sm" onClick={()=>setImportOpen(true)}><Plus size={17}/>匯入 Prompt</Button></div></header>
    <main id="main-content" className={home?'main-content':'main-content results-page'}>
      <section className="hero"><div className="hero-copy"><div className="section-eyebrow"><span className="eyebrow-line"/>{home?'A LITTLE LIBRARY OF POSSIBILITIES':'YOUR PERSONAL PROMPT LIBRARY'}</div><h1>{home?<>好用的 Prompt，<br/><em>隨時找到，隨手就用。</em></>:view==='recent'?<>回到上次的<em>好靈感。</em></>:category?<>{category}<em>，從這裡開始。</em></>:<>你的靈感，<em>都在這裡。</em></>}</h1><p>{home?'收藏值得留下的指令，把每一次好靈感，變成下一次的起點。':view==='recent'?'每一次複製都會留下紀錄，讓好用的範本更容易找回來。':'用你習慣的說法搜尋，找到範本，改一下就能開始。'}</p></div>{home&&<div className="hero-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="art-spark">✧</span><div className="index-card index-card-back"><span/><span/><span/></div><div className="index-card index-card-front"><span className="art-book"><BookOpen size={26} strokeWidth={1.3}/></span><div className="art-braces">{'{'}<span>idea</span>{'}'}</div><div className="art-rule"/><div className="art-lines"><i/><i/></div><small>一點靈感，無限可能。</small></div><span className="art-dot"/></div>}</section>
      <section className="search-section" aria-label="搜尋 Prompt"><div className={`search-box ${loading&&query?'searching':''}`}><Search size={23} strokeWidth={1.8}/><input ref={searchRef} aria-label="搜尋 Prompt" placeholder="今天想完成什麼？試試「寫季度報告的」" value={query} onChange={e=>setQuery(e.target.value)} autoComplete="off"/>{query?<button className="icon-button" onClick={()=>{setQuery('');searchRef.current?.focus();}} aria-label="清除搜尋"><X size={18}/></button>:<kbd>/</kbd>}<button className="search-submit" aria-label="開始搜尋" onClick={()=>{setRefresh(v=>v+1);searchRef.current?.focus();}}>{loading&&query?<LoaderCircle size={19} className="spin"/>:<ArrowRight size={21}/>}</button></div>
      {home?<div className="suggestions"><span>試試看</span>{['把文章變短','上次那個改履歷的','Midjourney 日系插畫'].map(text=><button key={text} onClick={()=>setQuery(text)}>{text}<ArrowUpRight size={12}/></button>)}</div>:<div className="filter-line"><span><Settings2 size={14}/>篩選</span><select aria-label="依分類篩選" value={category} onChange={e=>setCategory(e.target.value)}><option value="">所有分類</option>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select><select aria-label="依標籤篩選" value={tag} onChange={e=>setTag(e.target.value)}><option value="">所有標籤</option>{data?.tags.map(t=><option key={t}>{t}</option>)}</select>{(category||tag)&&<button onClick={()=>{setCategory('');setTag('');}}>清除篩選<X size={12}/></button>}</div>}</section>
      {home&&<section className="category-section"><div className="section-heading"><h2>從你想做的事開始</h2><button className="text-link" onClick={()=>setAllCategories(!allCategories)}>{allCategories?'收起分類':'瀏覽所有分類'}<ChevronRight size={14} className={allCategories?'rotate-down':''}/></button></div><div className="category-grid">{(allCategories?[...CATEGORIES]:featuredCategories).map((name,i)=><button className={`category-tile category-color-${i%6}`} key={name} onClick={()=>navigate('library',name)}><span className="category-symbol"><CategoryIcon name={name} size={22}/></span><strong>{name}</strong><span>{categoryDescriptions[name]??'找到適合你的範本'}</span><small>{data?.categories.find(c=>c.name===name)?.count??0} 則 Prompt</small></button>)}</div></section>}
      <section className="prompts-section"><div className="section-heading"><div className="heading-group"><h2>{home?(recent.length?'最近用過，接著好用':'先從這幾個範本開始'):query?`「${query.length>18?query.slice(0,18)+'…':query}」的搜尋結果`:view==='recent'?'最近使用的 Prompt':category||'所有 Prompt'}</h2>{!home&&<span className="count-chip">{loading?'…':visible.length}</span>}</div>{home?<button className="text-link" onClick={()=>navigate(recent.length?'recent':'library')}>查看全部<ArrowRight size={14}/></button>:view!=='recent'&&<div className="sort-control"><select aria-label="排序方式" value={sort} onChange={e=>setSort(e.target.value)}><option value="all">{query?'最相關':'最近加入'}</option><option value="popular">最常使用</option></select><ChevronDown size={13}/></div>}</div>
        {error?<div className="empty-state" role="alert"><Info size={30}/><h3>暫時無法載入辭典</h3><p>{error}</p><Button variant="outline" onClick={reload}>重新載入</Button></div>:loading&&!data?<div className="prompt-grid">{[0,1,2].map(i=><div key={i} className="skeleton-card"><i/><i/><i/></div>)}</div>:!visible.length?<div className="empty-state"><span className="empty-icon">{view==='recent'?<Clock3 size={28}/>:<Search size={28}/>}</span><h3>{view==='recent'?'下一個好用的 Prompt，從這裡開始':query?'還沒找到這個靈感':`這一頁，等你寫下第一則 Prompt`}</h3><p>{view==='recent'?'填好變數並複製後，它就會出現在這裡。':query?'換個說法試試，或把你已經有的 Prompt 匯入辭典。':'匯入常用的指令，慢慢累積屬於你的工作方式。'}</p><Button variant="outline" onClick={()=>view==='recent'?navigate('library'):setImportOpen(true)}>{view==='recent'?'瀏覽我的辭典':'匯入 Prompt'}<ArrowRight size={15}/></Button></div>:<div ref={resultsRef} className={`prompt-grid ${loading?'is-loading':''}`} aria-busy={loading}>{visible.map((p,i)=><article data-prompt-card key={p.id} className={`prompt-card ${selected===i?'card-selected':''}`}><div className="card-top"><span className="card-category"><CategoryIcon name={p.category} size={14}/>{p.category}</span><button className="icon-button" aria-label={`查看 ${p.title}`} onClick={()=>setDetail(p)}><ArrowUpRight size={17}/></button></div><button className="card-title" onClick={()=>setDetail(p)}>{p.title}</button><p className="card-summary">{p.summary}</p>{query&&p.highlight&&<p className="search-highlight"><Highlight value={p.highlight}/></p>}<div className="tag-list">{p.tags.slice(0,3).map(t=><button key={t} onClick={()=>{setTag(t);setView('library');}}>#{t}</button>)}</div><div className="card-bottom"><span>{p.last_used?<><Clock3 size={12}/>{relativeDate(p.last_used)}</>:<><span className="variable-symbol">{'{ }'}</span>{p.variables.length?p.variables.length+' 個可填變數':'直接使用'}</>}</span><button className="use-button" onClick={()=>void usePrompt(p)}>{p.variables.length?'填寫並複製':'一鍵複製'}<Copy size={14}/></button></div></article>)}</div>}
      </section>
      {home&&<section className="import-banner"><div className="banner-icon"><FolderOpen size={29} strokeWidth={1.3}/><span>+</span></div><div><h3>那些散落各處的好 Prompt，都收進來吧。</h3><p>貼上文字，或匯入 ChatGPT、Claude 匯出檔，整理成隨時可用的範本。</p></div><Button variant="outline" onClick={()=>setImportOpen(true)}><Upload size={16}/>開始匯入<ArrowRight size={15}/></Button></section>}
      <footer className="page-footer"><span><span className="status-dot"/>{pagesDemo?'瀏覽器示範版 · 私人收藏':'本機試用版 · 私人收藏'}</span><span>找到。改一下。拿去用。<Leaf size={13}/></span></footer>
    </main></div>
    <PromptDetail prompt={detail} onClose={()=>setDetail(null)} onSaved={p=>{setDetail(p);reload();}} notify={notify} onUsed={reload}/>
    <ImportDialog open={importOpen} onOpenChange={setImportOpen} onAccepted={()=>{reload();navigate('library');notify('已加入你的辭典，現在就能搜尋使用');}}/>
    <Modal open={helpOpen} onOpenChange={setHelpOpen} title="你的 Prompt，隨手就用" description="一些讓辭典更順手的小方法。"><div className="help-content"><h3><Keyboard size={18}/>鍵盤快捷鍵</h3><div className="key-row"><span>聚焦搜尋</span><kbd>/</kbd></div><div className="key-row"><span>選取搜尋結果</span><span><kbd>↑</kbd> <kbd>↓</kbd></span></div><div className="key-row"><span>使用選取的 Prompt</span><kbd>Enter</kbd></div><div className="key-row"><span>關閉視窗</span><kbd>Esc</kbd></div><div className="info-note"><Info size={18}/><div><strong>{pagesDemo?'這是可操作的網頁示範版':'這是可操作的本機版本'}</strong><p>{pagesDemo?'匯入、編輯與使用紀錄只儲存在目前瀏覽器。清除網站資料會刪除收藏，不會自動跨裝置同步。示範版使用關鍵字搜尋與規則整理，尚未連接正式 AI 與雲端帳號。':'匯入、編輯與使用紀錄會儲存在這台電腦。自動整理目前使用本機規則，正式 AI 與雲端帳號尚未連接。'}</p><p>{pagesDemo?'可透過瀏覽器選單加入主畫面。網站開啟後即可使用，無須啟動電腦上的服務。':'可透過瀏覽器選單安裝到桌面。使用時，請保持本機 App 服務開啟。'}</p></div></div></div></Modal>
    {toast&&<div className="toast" role="status"><CheckCheck size={18}/>{toast}<button onClick={()=>setToast('')} aria-label="關閉通知"><X size={15}/></button></div>}
  </div>;
}

function PromptDetail({prompt,onClose,onSaved,notify,onUsed}:{prompt:CardPrompt|null;onClose:()=>void;onSaved:(p:CardPrompt)=>void;notify:(s:string)=>void;onUsed:()=>void}) {
  const [values,setValues]=useState<Record<string,string>>({}),[error,setError]=useState(''),[copying,setCopying]=useState(false),[editing,setEditing]=useState(false),[fork,setFork]=useState(false),[draft,setDraft]=useState({title:'',body:'',summary:'',category:''});
  useEffect(()=>{if(prompt){setValues({});setError('');setEditing(false);setDraft({title:prompt.title,body:prompt.body,summary:prompt.summary,category:prompt.category});}},[prompt]);
  const preview=prompt?.body.replace(/\{\{([^{}]+)\}\}/g,(whole,name)=>values[name]||whole)??'';
  async function copy(){if(!prompt)return;setError('');let final:string;try{final=fillTemplate(prompt.body,prompt.variables,values);}catch(e){setError((e as Error).message);const missing=prompt.variables.find(v=>v.required&&!values[v.name]?.trim());if(missing)document.getElementById('variable-'+missing.name)?.focus();return;}setCopying(true);try{await navigator.clipboard.writeText(final);try{await api('/api/prompts/'+prompt.id,{method:'POST',body:JSON.stringify({action:'use',values,eventId:crypto.randomUUID()})});onUsed();notify('已複製，貼到你習慣的 AI 就能使用');}catch{notify('已複製，但使用紀錄暫時未儲存');}}catch{setError('瀏覽器未允許複製，請從右側預覽選取文字後複製。');}finally{setCopying(false);}}
  async function save(){if(!prompt)return;setError('');setCopying(true);try{const result=await api<CardPrompt>('/api/prompts/'+prompt.id,{method:'POST',body:JSON.stringify({action:'edit',...draft,fork})});onSaved(result);notify(fork?'新範本已加入辭典':'變更已儲存');}catch(e){setError((e as Error).message);}finally{setCopying(false);}}
  return <Modal open={!!prompt} onOpenChange={open=>{if(!open)onClose();}} title={editing?(fork?'另存一份新範本':'編輯 Prompt'):prompt?.title??'Prompt'} description={editing?'調整內容，用 {{變數名稱}} 保留可以替換的地方。':prompt?.summary??''} wide>{prompt&&<>
    {editing?<div className="editor-form"><label>名稱<input value={draft.title} maxLength={160} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div className="editor-row"><label>分類<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><label>一句話摘要<input value={draft.summary} onChange={e=>setDraft({...draft,summary:e.target.value})}/></label></div><label>Prompt 內容<textarea rows={11} value={draft.body} maxLength={24000} onChange={e=>setDraft({...draft,body:e.target.value})}/></label><small>已有相同本文時，請先修改內容再另存，避免重複收藏。</small></div>:<><div className="detail-meta"><span><CategoryIcon name={prompt.category} size={14}/>{prompt.category}</span><span>適用 {prompt.model_hint.length?prompt.model_hint.map(m=>m==='gpt'?'ChatGPT':m==='claude'?'Claude':'Midjourney').join(' / '):'各類 AI 模型'}</span><span>使用 {prompt.use_count} 次</span></div><div className="detail-grid"><section className="variable-panel"><div className="panel-label"><span>01</span><h3>改成你需要的內容</h3></div>{prompt.variables.length?<><p className="panel-description">填幾個空格，範本就準備好了。</p><button className="example-button" onClick={()=>setValues(Object.fromEntries(prompt.variables.map(v=>[v.name,v.example])))}>帶入範例值<ArrowDownSmall/></button>{prompt.variables.map(v=><label className="variable-field" key={v.name} htmlFor={'variable-'+v.name}>{v.label}{v.required&&<span className="required-dot"> *</span>}<textarea id={'variable-'+v.name} rows={/文章|內容|數據|程式碼/.test(v.name)?3:2} placeholder={v.example||`填入${v.label}`} value={values[v.name]??''} onChange={e=>setValues({...values,[v.name]:e.target.value})}/></label>)}</>:<div className="no-variables"><CheckCheck size={26}/><p>這則 Prompt 已經準備好了，<br/>直接複製就能使用。</p></div>}<div className="author-note"><span className="avatar avatar-small">我</span><div>我的私人收藏<small>{prompt.fork_of?'從其他範本修改而來':prompt.source==='fixtures/prompts.json'?'內建起始範本':'從 '+prompt.source+' 加入'}</small></div></div></section><section className="preview-panel"><div className="panel-label"><span>02</span><h3>你的 Prompt 預覽</h3><span className="live-label"><i/>即時更新</span></div><pre className="prompt-preview" tabIndex={0}>{preview}</pre><div className="preview-footer"><span>{preview.length} 字</span><span>填好的內容會自動出現在這裡</span></div></section></div></>}
    {error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-footer">{editing?<><Button variant="ghost" onClick={()=>setEditing(false)} disabled={copying}>返回範本</Button><Button onClick={()=>void save()} disabled={copying}>{copying?<LoaderCircle size={16} className="spin"/>:<Check size={16}/>}儲存{fork?'新範本':'變更'}</Button></>:<><div className="detail-edit-actions"><Button variant="ghost" size="sm" onClick={()=>{setFork(false);setEditing(true);}}><PenLine size={14}/>編輯</Button><Button variant="ghost" size="sm" onClick={()=>{setFork(true);setEditing(true);}}><FilePlus2 size={15}/>另存一份</Button></div><Button onClick={()=>void copy()} disabled={copying}>{copying?<LoaderCircle size={16} className="spin"/>:<Copy size={16}/>}複製完整 Prompt</Button></>}</div>
  </>}</Modal>;
}
function ArrowDownSmall(){return <ChevronDown size={13}/>;}

function ImportDialog({open,onOpenChange,onAccepted}:{open:boolean;onOpenChange:(value:boolean)=>void;onAccepted:()=>void}) {
  const [tab,setTab]=useState<'paste'|'file'>('paste'),[text,setText]=useState(''),[filename,setFilename]=useState(''),[job,setJob]=useState<ImportJob|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[dragging,setDragging]=useState(false);
  const fileRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{if(job?.status!=='processing')return;let stopped=false;let timer:ReturnType<typeof setTimeout>;async function poll(){try{const result=await api<ImportJob>('/api/imports/'+job!.id);if(stopped)return;setJob(result);if(result.status==='processing')timer=setTimeout(poll,400);}catch(e){if(!stopped)setError((e as Error).message);}}timer=setTimeout(poll,250);return()=>{stopped=true;clearTimeout(timer);};},[job?.id,job?.status]);
  async function file(file:File){setError('');if(!/\.(txt|md|json)$/i.test(file.name)){setError('請選擇 .txt、.md 或 .json 檔案');return;}if(file.size>10*1024*1024){setError('檔案太大，每批最多 10 MB');return;}setText(await file.text());setFilename(file.name);}
  async function start(){setBusy(true);setError('');try{setJob(await api<ImportJob>('/api/imports',{method:'POST',body:JSON.stringify({text,source:tab==='file'?filename:'貼上文字'})}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function accept(){if(!job)return;setBusy(true);setError('');try{await api('/api/imports/'+job.id,{method:'POST'});onAccepted();onOpenChange(false);setJob(null);setText('');setFilename('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const review=job?.status==='review',processing=job?.status==='processing';
  return <Modal open={open} onOpenChange={onOpenChange} title={review?'確認後，收進你的辭典':processing?'正在整理你的 Prompt':'把好用的 Prompt 收進來'} description={review?'已整理名稱、分類與可填變數，你的原始內容也會保留。':'貼上文字或上傳檔案，把散落的指令整理成可重複使用的範本。'}>
    <div className="import-content">{!job?<><div className="import-tabs" role="tablist" aria-label="匯入方式"><button role="tab" aria-selected={tab==='paste'} className={tab==='paste'?'active':''} onClick={()=>{setTab('paste');setText('');setFilename('');}}><MessageSquareText size={16}/>貼上文字</button><button role="tab" aria-selected={tab==='file'} className={tab==='file'?'active':''} onClick={()=>{setTab('file');setText('');setFilename('');}}><Upload size={16}/>上傳檔案</button></div>{tab==='paste'?<label className="paste-label">你的 Prompt<textarea rows={8} aria-label="貼上 Prompt 文字" value={text} onChange={e=>setText(e.target.value)} placeholder={'把你想保存的 Prompt 貼在這裡…\n\n多則 Prompt 請用獨立一行的 --- 分隔；空行會保留。\n已經有 {{變數}} 的範本也能直接匯入。'}/></label>:<button className={`upload-zone ${dragging?'is-dragging':''}`} onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);if(e.dataTransfer.files[0])void file(e.dataTransfer.files[0]);}} onClick={()=>fileRef.current?.click()}><span className="upload-icon">{filename?<FileText size={28}/>:<Upload size={28}/>}</span><strong>{filename||'把檔案拖曳到這裡'}</strong><span>{filename?'點擊更換檔案':'或點擊選擇檔案'}</span><small>.txt、.md、.json · 最大 10 MB</small></button>}<input ref={fileRef} type="file" accept=".txt,.md,.json" hidden onChange={e=>{if(e.target.files?.[0])void file(e.target.files[0]);e.target.value='';}}/><div className="import-explainer"><Check size={14}/>自動去除重複<Check size={14}/>辨識可填變數<Check size={14}/>確認後才加入</div><p className="local-note">支援 ChatGPT、Claude 的 JSON 匯出檔。示範版使用規則整理，內容不會送到雲端。</p></>:processing?<div className="import-progress"><span className="processing-orbit"><BookOpen size={32}/><LoaderCircle size={65} className="spin"/></span><h3>讓每個好靈感，都有自己的位置。</h3><p>正在切分、去重與整理範本</p><progress max={job.total||1} value={job.done}/><small>{job.total?`${job.done} / ${job.total} 則已整理`:'準備整理中…'}</small></div>:review?<><div className="review-summary"><span><strong>{job.items.length}</strong> 則可用範本</span><span>{job.duplicates+job.skipped} 則重複內容</span><span>{job.errors.length} 則未能整理</span></div>{job.items.length?<div className="review-list">{job.items.map(p=><details key={p.id}><summary><span className="review-check"><Check size={15}/></span><div><strong>{p.title}</strong><small>{p.category} · {p.variables.length} 個變數</small></div><ChevronDown size={16}/></summary><div className="review-body"><p>{p.summary}</p><pre>{p.body}</pre>{p.variables.map(v=><small key={v.name}>{'{{'+v.name+'}}'}{v.example?' · 範例：'+v.example:''}</small>)}</div></details>)}</div>:<div className="import-empty"><CheckCheck size={30}/><h3>這些靈感，已經在你的辭典裡了。</h3><p>沒有找到新的可匯入內容，也可能是文字少於 20 字。</p></div>}{job.errors.length>0&&<div className="form-error" role="alert">{job.errors.map(e=><p key={e.index}>第 {e.index+1} 則：{e.message}</p>)}</div>}</>:<div className="import-empty"><Info size={30}/><h3>這次沒能完成整理</h3><p>{job?.message}</p></div>}{error&&<p className="form-error" role="alert">{error}</p>}</div>
    <div className="modal-footer"><Button variant="ghost" disabled={busy} onClick={()=>{if(job&&!processing){setJob(null);setError('');}else onOpenChange(false);}}>{job&&!processing?'重新匯入':'稍後再說'}</Button>{!job?<Button disabled={busy||text.trim().length<20||(tab==='file'&&!filename)} onClick={()=>void start()}>{busy?<LoaderCircle size={16} className="spin"/>:<Sparkles size={16}/>}整理這些 Prompt</Button>:review&&(job.items.length>0||job.duplicates>0)?<Button disabled={busy} onClick={()=>void accept()}>{busy?<LoaderCircle size={16} className="spin"/>:<Plus size={16}/>}加入我的辭典{job.items.length>0?`（${job.items.length}）`:''}</Button>:processing?<span className="local-note">關閉視窗後會繼續整理</span>:null}</div>
  </Modal>;
}
